name: ai_accounting
description: An AI-powered accounting application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  crypto: ^3.0.3
  dart_openai_client:
    path: ../dart-openai-client
  dotenv: ^4.2.0
  get_it: any
  json_annotation: any
  meta: ^1.11.0
  path: any
  puppeteer: ^3.19.0
  test: any

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0 
